FROM harborretail/node-red:production

COPY ./flows.json /data/flows.json
COPY ./attract.html /data/content/attract.html
COPY ./attract.mp4 /data/content/attract.mp4
COPY ./resin-logo.png /data/content/resin-logo.png
